version: '3'

volumes:
  mysql:
    driver: local

services:

### App ##################################
    app:
      build:
        context: ./app
        args:
          - PHP_VERSION=${PHP_VERSION}
          - PGID=${APP_PUID}
          - PUID=${APP_PGID}
          - TZ=${APP_TIMEZONE}
          - INSTALL_ADDITIONAL_LOCALES=${APP_INSTALL_ADDITIONAL_LOCALES}
          - ADDITIONAL_LOCALES=${APP_ADDITIONAL_LOCALES}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_LUMEN_DIR}:cache
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:${APP_HOST_IP}"
      ports:
        - "${APP_SSH_PORT}:22"
        - "${APP_BROWSERSYNC_HOST_PORT}:3000"
        - "${APP_BROWSERSYNC_UI_HOST_PORT}:3001"
      tty: true

### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_LUMEN_DIR}:cache
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${WEB_HTTP_PORT}:80"
      depends_on:
        - php-fpm

### MySQL ################################################
    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${APP_TIMEZONE}
      volumes:
        - ${APP_HOST_DATA_DIR}/mysql:/var/lib/mysql
      ports:
        - "${MYSQL_PORT}:3306"