name: CI

on: [push, pull_request]

jobs:
  php_version: ["7.3", "7.4"]
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        PHP_VERSION: ${{ matrix.php_version }}
      run: |
        cp env-example .env
        docker-compose build app
